def lookup(name):
    d = {'0 Hz'   :['Branch.unconditional(0)'],
         '1 Hz'   :['BeamRequest(0)',
                    'FixedRateSync("1H",1)',
                    'Branch.unconditional(0)'],
         '10 Hz'  :['BeamRequest(0)',
                    'FixedRateSync("10H",1)',
                    'Branch.unconditional(0)'],
         '50 Hz'  :['BeamRequest(0)',
                    'FixedRateSync("100H",2)',
                    'Branch.unconditional(0)'],
         '100 Hz' :['BeamRequest(0)',
                    'FixedRateSync("100H",1)',
                    'Branch.unconditional(0)'],
         '500 Hz' :['BeamRequest(0)',
                    'FixedRateSync("1kH",2)',
                    'Branch.unconditional(0)'],
         '1 kHz'  :['BeamRequest(0)',
                    'FixedRateSync("1kH",1)',
                    'Branch.unconditional(0)'],
         '5 kHz'  :['BeamRequest(0)',
                    'FixedRateSync("10kH",2)',
                    'Branch.unconditional(0)'],
         '10 kHz' :['BeamRequest(0)',
                    'FixedRateSync("10kH",1)',
                    'Branch.unconditional(0)'],
         '31 kHz' :['BeamRequest(0)',
                    'FixedRateSync("910kH",30)',
                    'Branch.unconditional(0)'],
         '93 kHz' :['BeamRequest(0)',
                    'FixedRateSync("910kH",10)',
                    'Branch.unconditional(0)'],
         '186 kHz':['BeamRequest(0)',
                    'FixedRateSync("910kH",5)',
                    'Branch.unconditional(0)'],
         '929 kHz':['BeamRequest(0)',
                    'FixedRateSync("910kH",1)',
                    'Branch.unconditional(0)']}
    if name in d:
        return d['name']
    else:
        raise ValueError('{} not in sequence lookup'.format(name))
