from tools.seq import *

instrset = []
instrset.append( ControlRequest(511) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(15) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(31) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(15) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(63) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(15) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(31) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(15) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(127) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(15) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(31) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(15) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(63) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(15) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(31) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(15) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(255) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(15) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(31) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(15) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(63) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(15) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(31) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(15) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(127) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(15) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(31) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(15) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(63) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(15) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(31) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(15) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(7) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(3) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=1 ) )
instrset.append( Branch.unconditional(0) )
