from tools.seq import *

instrset = []
instrset.append( ControlRequest(63) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(7) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(7) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(15) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(7) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(7) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(15) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(7) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(7) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(31) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(7) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(7) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(15) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(7) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(7) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(15) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(7) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(7) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(31) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(7) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(7) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(15) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(7) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(7) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(15) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(7) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(7) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(3) )
# loop: req 1 of step 3 and repeat 1
start = len(instrset)
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( ControlRequest(1) )
instrset.append( FixedRateSync(marker=6, occ=3 ) )
instrset.append( Branch.unconditional(0) )
